[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
polygon_amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }

